# AUTH-SERVICE
server:
  port: 9001

spring:
  data:
    mongodb:
      database: NST-Shop-IdentityDB
      host: localhost
      port: 27017
  application:
    name: auth-service
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


jwt:
  secret: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
  type: JWT
  header: "Authorization"
  prefix: "Bearer "
  expire-time-access-token: 300000   # 5minute
  expire-time-refresh-token: 3600000  # 1hour