# USER-SERVICE
server:
  port: 9002
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nst-store-UserDB
    username: vantruong
    password: vantruong
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
