# API-GATEWAY
server:
  port: 9000
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-route
          uri: ${AUTH_ROUTE_URI:http://localhost:9001}
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
        - id: product-service-route
          uri: ${PRODUCT_ROUTE_URI:http://localhost:9002}
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product(?<remaining>.*), ${remaining}
        - id: order-service-route
          uri: ${ORDER_ROUTE_URI:http://localhost:9005}
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order(?<remaining>.*), ${remaining}
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

jwt:
  secret: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
  header: "Authorization"
  prefix: "Bearer "