# CART-SERVICE
server:
  port: 9004

spring:
  application:
    name: cart-service
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
management:
  endpoint:
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
