server:
  port: 9003
spring:
  # Email server config
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: vantruong.ct263ctu@gmail.com
    # https://myaccount.google.com/u/1/apppasswords
    password: ymwuovhcpviucpjn
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
